### ISSUE TITLE
Discolouration around transparent objects

### ISSUE THREAD

**Issue by daywink** [kisvegabor/lvgl#4040]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Discolouration around transparent objects

### To Reproduce
```c
    ui_Button1 = lv_btn_create(ui_callnum_top_nav);
    lv_obj_set_width(ui_Button1, 52);
    lv_obj_set_height(ui_Button1, 20);
    lv_obj_set_x(ui_Button1, -10);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); 
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE); 
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
```

### Expected behavior
Uniform background colour of the buttons and objects

### Screenshots or video
It doesn't show up very well on camera, but in person, it's very easy to spot.
![annotely_image](https://user-images.githubusercontent.com/65610123/223225454-65672d66-ab34-453b-8152-ae41d35f4a05.png)
Notice the different colour surrounding the border, when it should be uniform

![223225454-65672d66-ab34-453b-8152-ae41d35f4a05](https://user-images.githubusercontent.com/65610123/223227588-a1225d1f-5fc0-40f7-9201-c8387b97aedf.jpeg)
Digitally enhanced image to make the issue more visible.

https://user-images.githubusercontent.com/65610123/223226934-4fc3a93e-256f-46ca-bf7b-5c7b560e0bca.mov
Horizontal bar-like shape running through this button and gets taller when pressed.

This UI is exported from SquareLine Studio, there, there is no problem.

**Comment by kisvegabor** [comment]
Which LVGL version do you use? I think it was already fixed in the latest `v8.3` release. Please the the last commit from `release/v8.3` branch.

If it doesn't help:
- What is the color depth?
- Do you use any GPUs in the MCU?

**Comment by daywink** [comment]
Hi, I am already using the latest release. Here is my PlatformIO settings file:
```
lib_deps = 
        (...)
	lvgl=https://github.com/lvgl/lvgl/archive/refs/tags/v8.3.5.zip
        (...)
```
The colour depth is 16. My MCU does have a GPU, but I don't use it.

**Comment by daywink** [comment]
Just found out you are talking about something else, I will try it and let you know the result. I'm so sorry.

**Comment by daywink** [comment]
Tried out using `https://github.com/lvgl/lvgl/archive/refs/heads/release/v8.3.zip` as the library dependency, it does not help. The issue still remains.

**Comment by kisvegabor** [comment]
v8.3.5 should be fine.

I've trued to reproduce it wit this code:
```c
  lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t * ui_Button1 = lv_btn_create(lv_scr_act());
  lv_obj_set_width(ui_Button1, 52);
  lv_obj_set_height(ui_Button1, 20);
  lv_obj_set_x(ui_Button1, -10);
  lv_obj_set_y(ui_Button1, 0);
  lv_obj_set_align(ui_Button1, LV_ALIGN_LEFT_MID);
  lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
  lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Button1, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_Button1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_size(ui_Button1, 300, 100);
```

but can't see the issue.

Could you add a full code that reproduce the issue?

Other question: What is the value of `LV_COLOR_MIX_ROUND_OFS` in `lv_conf.h`. Please try wit 0, 128, and 254. Does it make any difference?

**Comment by daywink** [comment]
Changing `LV_COLOR_MIX_ROUND_OFS` does indeed seem to fix it.
I'm so sorry to bother you, but I don't know where to ask, can you give a simple example how to define keymap for `LV_KEYBOARD_MODE_USER_1`? I cant find info anywhere for it.

**Comment by daywink** [comment]
Figured it out on my own. Thanks.

**Comment by kisvegabor** [comment]
> Changing LV_COLOR_MIX_ROUND_OFS does indeed seem to fix it.

What was the original value (which showed the issue) and what is the new value (which solved it)?

> I'm so sorry to bother you, but I don't know where to ask, can you give a simple example how to define keymap for LV_KEYBOARD_MODE_USER_1? I cant find info anywhere for it.

You can take a look at how other maps are implemented [here](https://github.com/lvgl/lvgl/blob/release/v8.3/src/extra/widgets/keyboard/lv_keyboard.c#L49-L60).

You can also take a look at the docs [here](https://docs.lvgl.io/8.3/widgets/extra/keyboard.html#new-keymap).

**Comment by daywink** [comment]
Original value was the default from LV_CONF_INCLUDE_SIMPLE.

**Comment by daywink** [comment]
New value is 128 or 254, both fixed it.

**Comment by kisvegabor** [comment]
Thanks!
