### ISSUE TITLE
Double Buffering Optimization

### ISSUE THREAD

**Issue by bhspyder** [kisvegabor/lvgl#4262]
### Introduce the problem

When using a double buffered scenario (updating inactive buffer, wait for vsync, swap active buffer, repeat), there is a need to sync the changes made to the previous buffer. There are a number of examples as well as the current implementation recently added to master that do the following:
```
    for(i = 0; i < disp_refr->inv_p; i++) {
        if(disp_refr->inv_area_joined[i]) continue;
        disp_refr->draw_ctx->buffer_copy(
            disp_refr->draw_ctx,
            buf_off_screen, stride, &disp_refr->inv_areas[i],
            buf_on_screen, stride, &disp_refr->inv_areas[i]
        );
    }
```
The issue with this method is that it does not account for the fact that the next redraw could draw over the areas that were just synchronized making the synchronization for those areas unnecessary.

### Examples and cases

An optimization to this functionality to resolve the issue described above would be felt across the board in any animation, but would be realized the most during large area or full screen animations such as transitions, scrolling, or swiping when using double buffering. When doing full screen redraws, it would essentially be trying to write to the entire frame buffer twice during the refresh period which would put a huge unnecessary strain on the memory bandwidth.

### Suggested solution

There are a number of ways to resolve this, but a simple solution would be to delay the sync of the changed areas until after the next render and only sync previously changed areas that did not get changed during that render. Further optimization could be done to only update subregions of a previously changed area if part of it falls within an area changed by the latest render. I can look at putting a pull request together, but I wanted to create some discussion around whether this is something that would make sense to do within LVGL or not.

**Comment by pete-pjb** [comment]
Hi Brandon,

It's strange. I have been thinking exactly the same over the past couple of weeks.  I, for one, would be most grateful for your work.  My active projects use a screen resolution of 1440 x 900 using RGBA8888, so these types of enhancement all make big savings on CPU time.  I also use VNC, so it would help with CPU load for that as well.  I think @kisvegabor should comment on this also as I am not sure if all current rendering ideas are yet public with all the ongoing changes for parallel rendering/version 9?
I look forward to seeing your pull request.  If I can help, please feel free to ask...  I have limited time, but I will try and help if required. 

Cheers,

Pete

**Comment by kisvegabor** [comment]
Hi Brandon,

I was also thinking about something like this, but somehow such a clean approach didn't come to my mind. :slightly_smiling_face: 

So what we need to do is postponing the synchronization until the beginning of the the new redraw cycle where we already see the new areas to redraw. 

We also need smart algorithm which can decide which area to copy and redraw. I'm thinking about something like this:  
- if an `area_to_sync` is fully inside of any `area_to_redraw`, do not sync that area (no need to sync as it will be redrawn)
- if an `area_to_redraw` is fully inside of an `area_to_sync`, and the `area_to_sync` is only a little bit larger, redraw the area to sync instead.

What do you think?

**Comment by bhspyder** [comment]
Hi @kisvegabor,

Thanks for the quick response.

That seems like a good strategy. A few things that come to mind:
* We will need a second array to store invalidated areas from previous render (can exclude joined areas). Something like:
```
    /** Double buffer sync areas */
    lv_area_t sync_areas[LV_INV_BUF_SIZE];
    uint16_t sync_p;
```
* What happens in the cases where an `area_to_redraw` is only partially covering an `area_to_sync`? I guess one option could be to redraw the `area_to_sync`, but seems like removing the `area_to_redraw` from `area_to_sync` and splitting what remains into multiple smaller areas (area diff) for copying instead of rendering the whole thing may be more performant. Not sure how common this case would be though, so maybe not worth the effort?

**Comment by bhspyder** [comment]
I implemented only the first part of the algorithm (if an area_to_sync is fully inside of any area_to_redraw, do not sync that area (no need to sync as it will be redrawn) on v8.3.7 and there is a noticeable significant improvement. I will run some before and after benchmarks later to get specifics.

I would assume if I am making a PR, it would probably be on master not the latest v8.3?

**Comment by FASTSHIFT** [comment]
Hi every one, I have implemented the auto-detected minimum area synchronization algorithm, and I plan to submit a PR in the near future :>

**Comment by bhspyder** [comment]
Running the benchmark demo on custom hardware (STM32F746xx) with 1280x800 @ 16bpp:
* Without optimization: 22 fps-weighted
* With optimization 28 fps-weighted

Running the benchmark demo on custom hardware (STM32F746xx) with 1024x600 @ 16bpp:
* Without optimization: 40 fps-weighted
* With optimization 44 fps-weighted

Running the benchmark demo on custom hardware (STM32F746xx) with 800x480 @ 16bpp:
* Without optimization: 39 fps-weighted
* With optimization 44 fps-weighted

As expected, the fps gain was more significant the larger the LCD dimensions.

@kisvegabor Looking at the second part of the algorithm, how much would you consider "a little bit larger"? 10% larger area (width*height)?

@FASTSHIFT Would you be willing to share the algorithm now so I can compare with my current implementation?

**Comment by bhspyder** [comment]
For those interested, here is the sync function:
```
/**
 * Refresh the sync areas
 */
static void refr_sync_areas(void)
{
	/*Do not sync if no sync areas*/
	if (disp_refr->sync_p == 0) return;

	/*Do not sync if not double buffered*/
	if (!disp_refr->driver->direct_mode) return;

	/*The buffers are already swapped.
	 *So the active buffer is the off screen buffer where LVGL will render*/
	void * buf_off_screen = disp_refr->driver->draw_buf->buf_act;
	void * buf_on_screen = disp_refr->driver->draw_buf->buf_act == disp_refr->driver->draw_buf->buf1
						   ? disp_refr->driver->draw_buf->buf2
						   : disp_refr->driver->draw_buf->buf1;

	/*Iterate through invalidated areas to see if sync area should be copied*/
	bool sync;
	lv_coord_t stride = lv_disp_get_hor_res(disp_refr);
	uint32_t i, j;
	for(i = 0; i < disp_refr->sync_p; i++) {
		sync = true;
		for(j = 0; j < disp_refr->inv_p; j++) {

			/*Skip joined areas*/
			if (disp_refr->inv_area_joined[j]) continue;

			/*Sync area is fully inside inv area; Do not sync*/
			if (_lv_area_is_in(&disp_refr->sync_areas[i], &disp_refr->inv_areas[j], 0)) {
				sync = false;
				break;
			}
		}

		/*Sync area should be copied*/
		if (sync) {
			disp_refr->driver->draw_ctx->buffer_copy(
				disp_refr->driver->draw_ctx,
				buf_off_screen, stride, &disp_refr->sync_areas[i],
				buf_on_screen, stride, &disp_refr->sync_areas[i]
			);
		}
	}

	/*Reset sync area count*/
	disp_refr->sync_p = 0;
}
```

This gets called immediately before ``refr_invalid_areas()``

The sync areas are copied before the cleanup of the inv areas:
```
    /*If refresh happened ...*/
    if(disp_refr->inv_p != 0) {

    	/*Copy invalid areas for sync next refresh*/
    	if (disp_refr->driver->direct_mode)
    	{
			uint16_t i;
			for(i = 0; i < disp_refr->inv_p; i++) {
				if (disp_refr->inv_area_joined[i])
					continue;

				disp_refr->sync_areas[disp_refr->sync_p++] = disp_refr->inv_areas[i];
			}
    	}

        /*Clean up*/
        lv_memset_00(disp_refr->inv_areas, sizeof(disp_refr->inv_areas));
        lv_memset_00(disp_refr->inv_area_joined, sizeof(disp_refr->inv_area_joined));
        disp_refr->inv_p = 0;

        elaps = lv_tick_elaps(start);

        /*Call monitor cb if present*/
        if(disp_refr->driver->monitor_cb) {
            disp_refr->driver->monitor_cb(disp_refr->driver, elaps, px_num);
        }
    }
```

**Comment by pete-pjb** [comment]
Hi @bhspyder ,

This looks good to me.

I was wondering also if anyone else had thought about there being a method for a hardware interrupt to trigger the rendering/buffer copying based on the vertical sync or DMA processes rather than having an asynchronous software timer driving it from LVGL?

Does this seem like a sensible idea and a worthwhile optimisation to anyone else?

cc @kisvegabor 
cc @FASTSHIFT 

Kind Regards,

Pete

**Comment by bhspyder** [comment]
Hi @pete-pjb,

I have done this by deleting the refresh timer and triggering the update manually on vertical sync (as described in the documentation) to try and relax the external memory bandwidth. I don't remember there being a noticeable difference in performance, but it did provide some relief to the memory bandwidth.

**Comment by pete-pjb** [comment]
Hi @bhspyder ,

Thanks for pointing that out, it's a long time since I read the documentation as my project is long and I wrote my drivers way back when...  I think that method has been added since...  Okay I will withdraw my comment above as that is a perfectly acceptable solution, I'll give it a try on my platform.  Anything which saves memory bandwidth is good for me as my system uses multiple Arm AXI interfaces to DMA backward and forward to DDR RAM for various different peripherals.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Sorry for the late reply.

Thank you for the benchmarking, it's really useful. 
So we can count with 10-20% performance gain. Note that, in the current implementation the worst case scenario is when the whole screen needs to be redrawn as in this case we have an extra  full copy for nothing. And this case is not tested in benchmark. So the performance gain could be even higher.

> Looking at the second part of the algorithm, how much would you consider "a little bit larger"? 10% larger area (width*height)?

Let say there is a 100x100 `area_to_sync` and the middle of it there is a 80x80 `area_to_redraw`.  What can we do?
1. Sync the 100x100 area and draw the 80x80 one
2. Sync the 100x10 + 10x10 + 10x10 + 100x10 areas and draw the 80x80
3. Render the 100x100 area

Let say rendering takes 3 times more time then coping. For this we can calculate the cost of each option:
```
1) 100*100 + 80*80*3 = 29,200
2) 100*10 + 10*10 + 10*10 + 100*10 + 80*80*3 =   21,400
3) 100*100*3 = 30,000
```

If the rendering needs  5 times  more time 3) will be even worse. In 2) I didn't consider the overhead of calling copy but let's say it negligible compared to rendering. So it seems to be me the best we can do is copying in all cases and never extend the area to render. 
 
> What happens in the cases where an area_to_redraw is only partially covering an area_to_sync? 

Imagine that there is a 100x100 `area_to_redraw` and an other 100x100 `area_to_sync` and they have 1 common pixel. We could sync a 100x99 and 99x1 area and redraw the 100x100 area. What we lose is calling the copy twice and what we gain is not coping one pixel.

If the two area has an 50x50 area in common. We need to copy e.g. 100x50 and 50x50 and render 100x100. So we saved an 50x50 copy.

If they have 100x99 common area we need to copy 1x100 and render 100x100. So we saved 100x99 copy.

So we always need to render the `area_to_redraw` and usually make 2 copies. The question is after how many pixels  does the call of two copies pay off. Let's say starting the copy takes 100 instructions, and to copy a pixel takes 1 instruction. So larger than a 10x10 area it's worth having 2 copies instead of coping the extra area too. But this 10x10 area is so small that I'd say we can always do 2 copies for the sake of simplicity.

**Comment by bhspyder** [comment]
That makes sense @kisvegabor. 

To support this method, we will need a function that can return the remaining areas (max 4 I think) after subtracting the intersect between 2 areas (the difference). This will need to be executed against the sync areas and redraw areas that intersect to come up with a new list of areas to sync.

I will try and implement this and do some more benchmarking.

**Comment by kisvegabor** [comment]
Amazing, I'm looking forward to see the implementation and the benchmark result :slightly_smiling_face:

**Comment by bhspyder** [comment]
Quick update so this doesn't go stale. The first optimization was enough of an improvement that I have been assigned to other things so I haven't had time to look at this. I am still going to try and finish the implementation and package it up in a PR when I can.

**Comment by pete-pjb** [comment]
Hi @bhspyder ,

I can confirm I tried your code below and it certainly works well and provides an improvement in the performance of my hardware implementation.  So I look forward to seeing your completed work.  Thank you. 🙂 

Kind Regards,

Pete

> For those interested, here is the sync function:
> 
> ```
> /**
>  * Refresh the sync areas
>  */
> static void refr_sync_areas(void)
> {
> 	/*Do not sync if no sync areas*/
> 	if (disp_refr->sync_p == 0) return;
> 
> 	/*Do not sync if not double buffered*/
> 	if (!disp_refr->driver->direct_mode) return;
> 
> 	/*The buffers are already swapped.
> 	 *So the active buffer is the off screen buffer where LVGL will render*/
> 	void * buf_off_screen = disp_refr->driver->draw_buf->buf_act;
> 	void * buf_on_screen = disp_refr->driver->draw_buf->buf_act == disp_refr->driver->draw_buf->buf1
> 						   ? disp_refr->driver->draw_buf->buf2
> 						   : disp_refr->driver->draw_buf->buf1;
> 
> 	/*Iterate through invalidated areas to see if sync area should be copied*/
> 	bool sync;
> 	lv_coord_t stride = lv_disp_get_hor_res(disp_refr);
> 	uint32_t i, j;
> 	for(i = 0; i < disp_refr->sync_p; i++) {
> 		sync = true;
> 		for(j = 0; j < disp_refr->inv_p; j++) {
> 
> 			/*Skip joined areas*/
> 			if (disp_refr->inv_area_joined[j]) continue;
> 
> 			/*Sync area is fully inside inv area; Do not sync*/
> 			if (_lv_area_is_in(&disp_refr->sync_areas[i], &disp_refr->inv_areas[j], 0)) {
> 				sync = false;
> 				break;
> 			}
> 		}
> 
> 		/*Sync area should be copied*/
> 		if (sync) {
> 			disp_refr->driver->draw_ctx->buffer_copy(
> 				disp_refr->driver->draw_ctx,
> 				buf_off_screen, stride, &disp_refr->sync_areas[i],
> 				buf_on_screen, stride, &disp_refr->sync_areas[i]
> 			);
> 		}
> 	}
> 
> 	/*Reset sync area count*/
> 	disp_refr->sync_p = 0;
> }
> ```
> 
> This gets called immediately before `refr_invalid_areas()`
> 
> The sync areas are copied before the cleanup of the inv areas:
> 
> ```
>     /*If refresh happened ...*/
>     if(disp_refr->inv_p != 0) {
> 
>     	/*Copy invalid areas for sync next refresh*/
>     	if (disp_refr->driver->direct_mode)
>     	{
> 			uint16_t i;
> 			for(i = 0; i < disp_refr->inv_p; i++) {
> 				if (disp_refr->inv_area_joined[i])
> 					continue;
> 
> 				disp_refr->sync_areas[disp_refr->sync_p++] = disp_refr->inv_areas[i];
> 			}
>     	}
> 
>         /*Clean up*/
>         lv_memset_00(disp_refr->inv_areas, sizeof(disp_refr->inv_areas));
>         lv_memset_00(disp_refr->inv_area_joined, sizeof(disp_refr->inv_area_joined));
>         disp_refr->inv_p = 0;
> 
>         elaps = lv_tick_elaps(start);
> 
>         /*Call monitor cb if present*/
>         if(disp_refr->driver->monitor_cb) {
>             disp_refr->driver->monitor_cb(disp_refr->driver, elaps, px_num);
>         }
>     }
> ```

**Comment by pete-pjb** [comment]
Not Stale....

@bhspyder

**Comment by bhspyder** [comment]
No progress on this as of yet. Still planning on doing it, but if someone else wants to take a stab, feel free.

**Comment by pete-pjb** [comment]
Not stale

**Comment by bhspyder** [comment]
I found some time to work on the area diff algorithm. I implemented it outside of the LVGL project for simplicity. @kisvegabor please review the logic (should be able to build and run it with any C99 C compiler). If it looks good, I will do a formal pull request with the algorithm implemented.

https://github.com/bhspyder/area_diff/blob/master/area_diff.c

Should the pull request be made on on the 8.3 stream or master? I was thinking that the dual fb auto sync feature should probably be optional as there may be implementations that do not want/need this.

**Comment by kisvegabor** [comment]
Amazing! Could you send the PR to master? This way we could easily test it and see the changes as a whole.

**Comment by bhspyder** [comment]
Ported my original changes to master (v9) and the fb sync appears to be working. Transparency blending appears to no longer be working on master. I can't see the perf monitors and the music demo is drawing the animation on top of the image. I am using LV_COLOR_DEPTH 16 (RGB565). Is there something new in v9 that I need to do to enable blending?

**Comment by bhspyder** [comment]
Here are some benchmarks of the algorithm on v8.3.7:

Custom hardware (STM32F746xx with 1280x800 @ 16bpp):
* Without any optimization (v8.3.7): 20 fps-weighted
* With phase 1 (previous) optimization: 28 fps-weighted
* With phase 2 (new) optimization: 34 fps-weighted

Custom hardware (STM32F746xx with 800x480 @ 16bpp):
* Without any optimization (v8.3.7): 39 fps-weighted
* With phase 1 (previous) optimization: 44 fps-weighted
* With phase 2 (new) optimization: 55 fps-weighted

Custom hardware (STM32F746xx with 480x854 @ 16bpp):
* Without any optimization (v8.3.7): 50 fps-weighted
* With phase 1 (previous) optimization: 53 fps-weighted
* With phase 2 (new) optimization: 67 fps-weighted

**Comment by kisvegabor** [comment]
Woooow, it's amazing! ~30-50 performance boost! 

> However, alpha blending appears to no longer be working correctly in my project on master. 

I've tried it out and there really was bug there. I've just pushed a fix. Due to this bug nothing was copied, probably that's why v9 was faster than v8.  I'm really curious how v9 performs compared to v8 in your tests.

**Comment by kisvegabor** [comment]
Thank you for the PR! I'll test it probably tomorrow.

**Comment by bhspyder** [comment]
No problem! I was able to do some basic testing and the sync is working as expected, but I am not able to do any benchmarking until I figure out why my project isn't playing nice with v9.

**Comment by bhspyder** [comment]
If everything checks out, what are your thoughts on getting this into the v8.3 stream as well? I don't see my project moving to v9 for production until a more official release and it would be nice to switch from my fork to official releases of v8.3.

**Comment by pete-pjb** [comment]
Hi @bhspyder ,

Thanks for this valuable addition to LVGL. 

I for one will definitely use this in V8 so  you have my vote!

Kind Regards, 

Pete

**Comment by kisvegabor** [comment]
I've just tested it, and it works to me in the simulator.

> There appears to be an issue with layering. Some of the layers are being covered by others incorrectly

Could you send a video or photo about it? Can I reproduce it somehow?

> Part way through the benchmark, it will freeze. Debugging shows a failed tlsf_assert() in block_locate_free(). It was expecting the block size to be 3600 and only got 2.

On which step does it fail?

**Comment by kisvegabor** [comment]
I've found a bug in benchmark with 16 bit color depth and fixed it here: 7fb3d7eb3

I saw that at the end of the bechmark some step are not rendered with 16 bit. I'll check it, but it wasn't crashing for me.

**Comment by bhspyder** [comment]
Layering issues:
![image](https://github.com/lvgl/lvgl/assets/97706724/1ef88293-2ba4-498f-b424-f455f56dbb40)

![image](https://github.com/lvgl/lvgl/assets/97706724/cd3d1987-6f45-4ea3-988d-dd63eed302d4)

![image](https://github.com/lvgl/lvgl/assets/97706724/23a8e82d-0caf-49e7-bf2a-bb790e27da05)

![image](https://github.com/lvgl/lvgl/assets/97706724/71609461-839d-4a75-ac1b-a7cc07522ea3)

The music demo appears to have some corrupt images as well.

The benchmark is freezing at the end of the Image RGB recolor + opa step. Here:
![image](https://github.com/lvgl/lvgl/assets/97706724/d7f2c092-d8f5-477e-bd6d-da780594d8d4)

**Comment by kisvegabor** [comment]
The issues with the widgets demo are normal, it's just not fully updated yet. So not the issue of rendering but the demo itself.

I'm looking into the music player demo. I need to find the image assets to convert them again :sweat_smile: 

> The benchmark is freezing at the end of the Image RGB recolor + opa step.

I've fixed the issue of the next step in https://github.com/lvgl/lvgl/commit/7fb3d7eb389034a20598cd745922a27222a2330c

In general I would say it's working but there are some local issues here and there. 

What was the difference between first few steps of the benchmark in v9 with and without your changes?

Using the benchmark in general it's hard to compare v8 to v9 as we needed to fix a few things about how it measures the time and FPS.

**Comment by bhspyder** [comment]
> The issues with the widgets demo are normal, it's just not fully updated yet. So not the issue of rendering but the demo itself.
> 
> I'm looking into the music player demo. I need to find the image assets to convert them again 😅

Good to know. I won't worry about that then.

> I've fixed the issue of the next step in [7fb3d7e](https://github.com/lvgl/lvgl/commit/7fb3d7eb389034a20598cd745922a27222a2330c)
> 
> In general I would say it's working but there are some local issues here and there.

I checked out the latest but it didn't resolve my issue. I was using LV_DEMO_BENCHMARK_MODE_REAL and changing it to LV_DEMO_BENCHMARK_MODE_RENDER_AND_DRIVER allows me to complete all of the steps in the benchmark.

> What was the difference between first few steps of the benchmark in v9 with and without your changes?

Running the benchmark with LV_DEMO_BENCHMARK_MODE_RENDER_AND_DRIVER, I am not seeing any real FPS differences between master and the branch in my pull request. I'm not sure why there would be such a drastic difference on v8.3, but not on v9.

**Comment by kisvegabor** [comment]
> I checked out the latest but it didn't resolve my issue. I was using LV_DEMO_BENCHMARK_MODE_REAL and changing it to LV_DEMO_BENCHMARK_MODE_RENDER_AND_DRIVER allows me to complete all of the steps in the benchmark.

Does the benchmark fail on the same step?

> I'm not sure why there would be such a drastic difference in the benchmark on v8.3, but not on v9. Running the widgets demo with perf monitors, I can see the same gains on v9 I got on v8.3. It is noticeably smoother.

So it seems there is a gain in v9 too, which is visible in the widgets demo, but doesn't shown in FPS of the benchmark. Is the correct?

How did v8 compared to v9 feel in general? Did v9 feel faster, slower or same as v8 with the widgets demo?

**Comment by kisvegabor** [comment]
> There is definitely a gain in the widgets demo that can be see by watching the FPS monitor.

In case of the benchmark REAL mode, the FPS is limited by `LV_DEF_REFR_PERIOD` (lv_conf.h). Even if it as rendered in 1 ms, it will write 30 FPS (1000 / LV_DEF_REFR_PERIOD). What is you change `LV_DEF_REFR_PERIOD` to 1?

> I would say v9 feels faster in general even before I applied the algorithm it was noticeably smoother.

I'm super happy now  :tada: :rocket: And the STM GPU is not integrated yet with the parallel rendering update. 
Rewriting the half library always has the risk that the result will be worse than it was before. :smile:

**Comment by bhspyder** [comment]
I will try running the benchmark again with LV_DEF_REFR_PERIOD set to 1. I am looking forward to seeing how it performs with DMA2D integration. Is the parallel rendering framework already in place, you just need a DMA2D implementation? I may be interested in pursuing that if no one is actively working on it.

The last thing I need to figure out on my hardware is rotation. Since we are using direct frame buffer mode, the current software rotation implementation is not working. We lack the necessary memory to use a small draw buffer for software rotation. I'm thinking that the render code will need to be modified so that it writes it into the frame buffer at the correct orientation.

**Comment by bhspyder** [comment]
I was able to complete the benchmark using LV_DEMO_BENCHMARK_MODE_REAL with LV_DEF_REFR_PERIOD set to 1. I got a weighted FPS of 33 with the algorithm and 21 without. 

Afterwards I merged in the latest changes in master into my branch and a number of things are broken. Namely there appears to be a typo in lv_mem_core_builtin.c:83 causing a build error if LV_MEM_ADDR does not equal 0. After fixing the build error, it freezes after drawing the first frame no matter which demo I am using. This appears to be the case whether I am using my branch or the latest master. I haven't debugged it yet. Just first observation.

@kisvegabor  Any objection to me making a pull request for the v8.3 stream as mentioned before?

**Comment by kisvegabor** [comment]
> Is the parallel rendering framework already in place, you just need a DMA2D implementation? I may be interested in pursuing that if no one is actively working on it.

The parallel rendering update is mainly there, but I'm still having meeting  with STM. I can't tell the details yet, but please wait a little bit with the implementation as there are some open business related questions which might affect how we will approach ST's GPU support.

 >  I'm thinking that the render code will need to be modified so that it writes it into the frame buffer at the correct orientation.

Unfortunately it's out of scope now. It'd be a quite complex update with many pitfalls and it's not planned for now, sorry. :slightly_frowning_face: 


> I was able to complete the benchmark using LV_DEMO_BENCHMARK_MODE_REAL with LV_DEF_REFR_PERIOD set to 1. I got a weighted FPS of 33 with the algorithm and 21 without.

Amazing! It's 50% improvement! 

> Afterwards I merged in the latest changes in master into my branch and a number of things are broken. Namely there appears to be a typo in lv_mem_core_builtin.c:83 causing a build error if LV_MEM_ADDR does not equal 0. After fixing the build error, it freezes after drawing the first frame no matter which demo I am using. This appears to be the case whether I am using my branch or the latest master. I haven't debugged it yet. Just first observation.

Could you send a PR for that typo? I don't know what causes the problem, it works well on my end.

> Any objection to me making a pull request for the v8.3 stream as mentioned before?

Please send a PR, if it's really working we can merge it! I'll try it out when the PR is opened.

**Comment by bhspyder** [comment]
@kisvegabor Here is the PR for the typo: https://github.com/lvgl/lvgl/pull/4496. I was able to fix the "freezing" issue by setting a tick callback instead of setting the custom get tick in lv_conf.h. I wasn't aware of that change.

I caught my v9 pull request up to latest in master and will be making a v8.3 shortly.

**Comment by bhspyder** [comment]
v8.3 PR: https://github.com/lvgl/lvgl/pull/4497

**Comment by kisvegabor** [comment]
>  I was able to fix the "freezing" issue by setting a tick callback instead of setting the custom get tick in lv_conf.h. I wasn't aware of that change.

Ah sorry, a lot of things are still changing...

**Comment by kisvegabor** [comment]
Let continue in https://github.com/lvgl/lvgl/pull/4443#issuecomment-1726389193
