### ISSUE TITLE
Rotating a style only works twice for the entire code.

### ISSUE THREAD

**Issue by XanCraft21** [kisvegabor/lvgl#4822]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Hello, i don’t know if anyone else is having this issue or is it just me. If i were to rotate a style multiple times the rotation only works 2 times then stops rotating, the code still runs normally. I want to make a style spin around repeatedly.

I know this has worked before but it not longer works since version 8.3, which is the version i am currently using. It appears to work once or twice entirely, and i’m not sure why.

I also realized that the same thing happens to the zoom function. I don’t know what to do.

I may have done the simulator poorly, but i will try again if requested. I hope you can help me figure this out, thank you for the help.

Version: release 8.3
Platform: Arduino
Operating system: Windows 10
CPU: teensy 4.0 ARM Cortex M7

### To Reproduce

Provide a small, independent code sample that can be used to reproduce the issue.
Ideally this should work in the PC simulator unless the problem is specific to a platform.
Format the code like this:
```c
// Create an object we will modify later
lv_obj_t *obj1;

void setup() {
  // Let’s say we already have our display setup and working.

  // Create a color
  lv_color_t bg_c = lv_color_make(255, 0, 0);

  // Create a style
  static lv_style_t style_fill;
  lv_style_init(&style_fill);
  lv_style_set_bg_color(&style_fill, bg_c);

  // Modify the object we made earlier
  obj1 = lv_obj_create(lv_scr_act());
  lv_obj_set_size(obj1, 100, 100);
  lv_obj_set_pos(obj1, 0, 0);
  lv_obj_add_style(obj1, style_fill, 0);
  lv_obj_align(obj1, LV_ALIGN_CENTER, 0, 0);

  // Set rotation for the object
  lv_obj_set_style_transform_pivot_x(obj1, 50, 0);
  lv_obj_set_style_transform_pivot_y(obj1, 50, 0);
  lv_obj_set_style_transform_angle(obj1, 0, 0);
}

// Make some rotation variables
int angleAdd = 0;
Int angleInc = 10;
Int angleMax = 3600;

void loop() {
  angleAdd += angleInc;

  // Optional, keep angle from overflowing

  if (angleAdd >= angleMax) {
    angleAdd -= angleMax;
  }

  if (angleAdd <= -angleMax) {
    angleAdd += angleMax;
  }

  // Rotate our style forever
  lv_obj_set_style_transform_angle(obj1, angleAdd, 0);

  lv_timer_handler();
  delay(1);
}
```

### Expected behavior

The style should simply spin around forever.

### Screenshots or video

I will add these later.

**Comment by kisvegabor** [comment]
I think it's an out of memory issue. Can you increase `LV_MEM_SIZE` in `lv_conf.h`?

**Comment by XanCraft21** [comment]
Unfortunately that did not fix the problem. Then i tried increasing the size of LV_DISP_ROT_MAX_BUF and it still doesn’t work. The code still runs normally but no rotation happens.

I also tried enabling debug mode to see if any errors occur but i get no errors.

**Comment by kisvegabor** [comment]
Please enable all `LV_USE_ASSERT`s in `lv_conf.h` and the [logging](https://docs.lvgl.io/8.3/porting/log.html). Hopefully it will tell something useful.

**Comment by XanCraft21** [comment]
Sorry it too me all day to get back with you.

I turned on those settings and saw nothing. But i got it to work, but it took a while. I hope I didn’t waste an issue.

i had a warning saying i wasn’t calling lv_tick_inc(), so i did that and it started working, but it kept crashing after so long. I tried slowly increasing the memory usage and it was still acting strange.

I eventually turned on LV_TICK_CUSTOM and LV_MEM_CUSTOM and those problems went away.

To me it seems like using the built-in memory allocation is very buggy. I think i have fixed my problem now. This library is pretty hard to set up, but I usually use libraries that need little changes.

Thank you for your help, and sorry if i wasted an issue. I will close this soon.

**Comment by kisvegabor** [comment]
Happy to hear that you could make it work. And also sorry for that it took more time than anticipated. I would like to understand what caused the biggest issue to get started, so that I can improve it. So could you tell how we could make the get started experience better?

**Comment by XanCraft21** [comment]
I’m not the greatest at making ideas for certain things. I just think the getting started and setup stuff is a bit complicated. I personally prefer more simple things, but that’s just me. Is there a possible way to simplify things?

**Comment by kisvegabor** [comment]
All the feedback matters. If something is too complicated for you, probably it is for other as well.

However I still can't see which part was too complicated:
- integrating LVGL into your project?
- configuring LVGL?
- making it work with your display?
- how to create widgets, styles, events, etc?
- where to learn the basics?
- language barriers?
- anything else?

**Comment by XanCraft21** [comment]
To me it’s mostly the configuring part that’s complex. I currently don’t have an active project to integrate this into, I mostly just mess around with the code just for fun. I’ll need to dive deeper with using the library to find out what else is complex or what i might run into.

As i said before i mostly usually use libraries that already have most of the things ready to go, and this is pretty new for me. It will take me some time to get used to using this library.

It could be because i was trying to go into things too fast, my biggest problem was the timers and memory usage. If it would be ok to add extra instructions for that or possibly some extra preconfigured default settings to make it easier?

**Comment by kisvegabor** [comment]
In this case I will think about how to make LVGL even less configuration free or more obvious to know what you can/should adjust. 

Thank you for the input!

**Comment by XanCraft21** [comment]
You’re welcome! I think i will close this now.
